# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: jupyter-session-transfer
has_binder: true
has_settings: true
kind: server
labextension_name: jupyter-session-transfer
project_short_description: A JupyterLab session tranfer extension.
python_name: jupyter_session_transfer
repository: https://github.com/MRyutaro/jupyter-session-transfer
test: true

